variables:
- group: Github-credentials
- group: artifactory-docker
- name: imageName
  value: go-exporter  # name of the image

name: '$(imageName) $(GitVersion.FullSemVer)'

trigger:
  branches:
    include:
    - develop

pr:
  branches:
    include:
    - '*'  # Include all branches for PR triggers

resources:
  repositories:
    - repository: templates
      type: github
      name: Germanedge/azure-pipelines-templates
      endpoint: Germanedge

extends:
  template: azure-pipelines-docker-template.yml@templates
  parameters:
    # activates new temlate
    templateVersion: 2
    kubernetesManifestBuilding: false
    stackDefinitionUpdating: false
    preDockerBuildStages:
    - stage: automatic_tests
      displayName: 'Automatic tests with SonarQube'
      pool:
        vmImage: 'ubuntu-24.04'
      dependsOn: update_version
      jobs:
      - job: tests
        displayName: Tests
        steps:
        - task: GoTool@0
          displayName: 'Install Go'
          inputs:
            version: '1.25.0'
        - task: Go@0
          displayName: 'Get dependencies'
          inputs:
            command: get
            arguments: -d
            workingDirectory: $(System.DefaultWorkingDirectory)
        - task: Go@0
          displayName: Test
          inputs:
            command: test
            arguments: -v
            workingDirectory: $(System.DefaultWorkingDirectory)
