# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/go?view=azure-devops&tabs=go-current


trigger:
  - master
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: GoTool@0
    displayName: 'Install Go'
    inputs:
      version: '1.20.4'
  - task: Go@0
    displayName: 'Get Dependencies'
    inputs:
      command: 'get'
      arguments: '-d'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: Go@0
    displayName: 'Build'
    inputs:
      command: 'build'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: CopyFiles@2
    displayName: 'Copy Files'
    inputs:
      sourceFolder: '$(System.DefaultWorkingDirectory)'
      contents: '**/go-exporter'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'go-exporter'
