# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/go?view=azure-devops&tabs=go-current


trigger: none
pr:
  branches:
    include:
      - master
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: GoTool@0
    displayName: 'Install Go'
    inputs:
      version: '1.20.5'
  - task: Go@0
    displayName: 'Get dependencies'
    inputs:
      command: 'get'
      arguments: '-d'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: Go@0
    displayName: 'Build'
    inputs:
      command: 'build'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: CopyFiles@2
    displayName: 'Copy files'
    inputs:
      sourceFolder: '$(System.DefaultWorkingDirectory)'
      contents: '**/id-exporter'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: Go@0
    displayName: 'Test'
    inputs:
      command: 'test'
      arguments: '-v'
      workingDirectory: '$(System.DefaultWorkingDirectory)'